id: A8AB38499
title: 'The Supreme Bestowal of Twofold Attainment: A Prayer to Orgyen Rinpoche, Embodiment
  of All Sources of Refuge'
type: translation
pechas:
- I3A7A7757
- I6613A74F
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:11:40.979936
  last_modified_at: 2023-01-04 12:11:40.979942
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I3A7A7757/9040: 4A8F
  I6613A74F/080B: 4A8F
